### ISSUE TITLE
Improvement: Untangled config loading

### ISSUE THREAD

**Issue by claudiuapetrei** [awkay/untangled#15]
Found it a bit strange that I have to pass untangled sever the config path, and there is no option for me to send it the config. Don't really know if it's a feature that adds value.

A few cases that come to mind would be validation of config before start, reading something from config outside of `stuartsierra/component`. 

Think I can make this work, with the existing flow. But as a preference I would lean towards reading the config and sending the config to untangled. There seem to be some a few libraries out there like https://github.com/tolitius/cprop 

A possible solution for maintaining backwards compatibility and just adding more flexibility would be: 
- untangled accepting `:config` or `:config-path`. 
- if config is sent config-path is ignored

**Comment by awkay** [comment]
Config (the component) will be the first thing that starts. Dozens of components can add their own config requirements to the config file...there is no way to make an extensible config system where you pre-validate without having to then compose it. As components start, they validate their interest in config, and exit with an error if there is a problem.

**Comment by claudiuapetrei** [comment]
@awkay agh ok. Still getting used to `sierra/component` flow.

Was thinking in dev/user.clj to add the database migrations. But you're right, then to have hot code reload for configs also I would have to add the reading part in the `go`, `start` functions. 

Was just tying to map my usual python dev flow to clojure/untangled.

Thank you :)
