### ISSUE TITLE
Always an empty option on dropdown

### ISSUE THREAD

**Issue by chrismurrph** [awkay/untangled#4]
Here's the state I have for a dropdown:

    :request/period
         {:input/type :untangled.ui.forms/dropdown,
          :input/default-value :untangled.ui.forms/none,
          :input/options
          [{:option/key :q1, :option/label "Q1"}
           {:option/key :q2, :option/label "Q2"}
           {:option/key :q3, :option/label "Q3"}],
          :input/css-class "",
          :input/name :request/period}}

When interacting with it there are always 4 possibilities, the 3 shown above in `:input/options`, plus another, the 'nothing' option. I don't want the 'nothing' option to be there. Is there a way to specify that the three options given are all I want the user to be able to pick from?

**Comment by awkay** [comment]
Set the default.
